### PR TITLE
Create storage_options and active_storage_url API

### LINKED ISSUE #177: Create storage_options and active_storage_url API
Create storage_options and active_storage_url API so that they are not  hardwired

### PR DESCRIPTION
**Pull request by davidhassell**
## Description
Create storage_options and active_storage_url API so that they are not hardwired

Closes #177

## Before you get started

- [x] [☝ Create an issue](https://github.com/valeriupredoi/PyActiveStorage/issues) to discuss what you are going to do

## Checklist

- [x] This pull request has a descriptive title and labels
- [x] This pull request has a minimal description (most was discussed in the issue, but a two-liner description is still desirable)
- [x] Unit tests have been added (if codecov test fails)
- [x] Any changed dependencies have been added or removed correctly (if need be)
- [ ] All tests pass

### CODE REVIEW

**Comment by davidhassell** [comment]
Hi V - only one test fails ... and a "mock" think which I'll have to pass on to you!

**Comment by valeriupredoi** [comment]
this is cool, cheers @davidhassell :beer: - my plan for this is:
- streamline and merge #180 first
- off the back of the new `main`, open a local PR (not messing about with forks)
- merge this in that
- add optional logon options for anon buckets integrated via this PR, when @markgoddard enables anon buckets in Reductionist
- plop a GH Actions test to test this and the anon bucket storage via the newly deployed Reductionist on @bnlawrence 's cloud machine
- merge
- then open a new PR allowing user specified config/logon options (bottom of the pile)

:beer:

**Comment by valeriupredoi** [comment]
bugger - time to sort out conflicts now :face_exhaling:

**Comment by valeriupredoi** [comment]
actually - too much time wasted fixing conflicts - gonna lift and drop from here, rather

**Pull request closed without merging**
