### PR TITLE
Streamline call to `kerchunk.SingleHdf5ToZarr` and add some performance metrics

### LINKED ISSUE #140: NetCDF to Zarr translation downloads chunk data from S3
Found while testing a local PyActiveStorage installation against a remote Reductionist/Minio setup, with a slow connection between them. Steps to reproduce:

* Add config to activestorage/config.py to access the remote Reductionist and Minio servers
* Upload some data to Minio in bucket `test`, object `test.nc` (mine was a 68MB CMIP6 dataset)
* Execute the following python script:
```python
import activestorage.active
import time

start = time.time()
a = activestorage.active.Active('s3://test/test.nc', 'ta', storage_type='s3')
inited = time.time()
a.method = 'mean'
a[:]
reduced = time.time()
print(f"Time to init: {inited - start:.2f}")
print(f"Time to reduce: {reduced - inited:.2f}")
```
We can see from the timings that this is very slow:

```
Time to init: 15.17
Time to reduce: 226.65
```

Using a network bandwidth monitor such as `iftop` we can see the entire file is transmitted to the client during the reduction. If we Ctrl-C during the reduction (after the metadata has been printed), we see the following backtrace, showing it's in `load_netcdf_zarr_generic`:

```
  File "/home/mark/src/PyActiveStorage/timeit.py", line 9, in <module>
    a[:]
  File "/home/mark/src/PyActiveStorage/activestorage/active.py", line 190, in __getitem__
    return self._via_kerchunk(index)
  File "/home/mark/src/PyActiveStorage/activestorage/active.py", line 300, in _via_kerchunk
    ds = nz.load_netcdf_zarr_generic(self.uri,
  File "/home/mark/src/PyActiveStorage/activestorage/netcdf_to_zarr.py", line 82, in load_netcdf_zarr_generic
    gen_json(fileloc, fs, fs2, out_json.name)
  File "/home/mark/src/PyActiveStorage/activestorage/netcdf_to_zarr.py", line 18, in gen_json
    h5chunks = SingleHdf5ToZarr(infile, file_url, inline_threshold=0)
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/kerchunk/hdf.py", line 92, in __init__
    self._h5f = h5py.File(self.input_file, mode="r")
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
  File "h5py/h5fd.pyx", line 163, in h5py.h5fd.H5FD_fileobj_read
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/fsspec/spec.py", line 1713, in readinto
    data = self.read(out.nbytes)
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/fsspec/spec.py", line 1703, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/fsspec/caching.py", line 157, in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/s3fs/core.py", line 2156, in _fetch_range
    return _fetch_range(
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/s3fs/core.py", line 2329, in _fetch_range
    return sync(fs.loop, _inner_fetch, fs, bucket, key, version_id, start, end, req_kw)
  File "/home/mark/src/PyActiveStorage/venv/lib/python3.10/site-packages/fsspec/asyn.py", line 88, in sync
    if event.wait(1):
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
```

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

@markgoddard found out in #140 that there is some hefty data transfer at the point where `kerchunk.SingleHdf5ToZarr` is called and run; that's not clear to me if that is actual data (as in, netCDF file's `data` member) transferred, or it's metadata, or it's something else; but I noticed that the [SingleHdf5ToZarr API docs](https://fsspec.github.io/kerchunk/reference.html#kerchunk.hdf.SingleHdf5ToZarr) mention the need for a `storage_options` dict to be passed to fsspec when the file is a string, so I thought we'd create that, pass it, and use it, see if it makes any difference at all.

Closes #140 (well, at least attempts to, if testing proves otherwise, we'll take it from there)

## Before you get started

- [x] [☝ Create an issue](https://github.com/valeriupredoi/PyActiveStorage/issues) to discuss what you are going to do

## Checklist

- [x] This pull request has a descriptive title and labels
- [x] This pull request has a minimal description (most was discussed in the issue, but a two-liner description is still desirable)
- [x] All tests pass

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@markgoddard no more need to test with your test in #140 - I have implemented here actual pytest monitoring that measures memory used by individual tests - look at "Analyze S3 performance" in the GA test - it is clear that the S3 with AS is using almost exactly as much memory as the no AS case - this means only one thing - data loaded in the client's memory :confounded: :confounded: There is definite data transfer, most probably in kerchunk - I need to look much closer at this, in this PR

**Comment by valeriupredoi** [comment]
OK we got out culprit for sure - smoking gun held by `SingleHdf5ToZarr`:
```
test_Active 881.75390625
test_no_Active 877.3359375
test_s3_SingleHdf5ToZarr 928.3359375
test_local_SingleHdf5ToZarr 890.296875
List of 100 slowest tests (duration, path, name
2.89s test_s3_performance.py::test_Active
2.40s test_s3_performance.py::test_s3_SingleHdf5ToZarr
0.18s test_s3_performance.py::test_local_SingleHdf5ToZarr
0.15s test_s3_performance.py::test_no_Active
```

**Comment by valeriupredoi** [comment]
OK gents @markgoddard @bnlawrence @davidhassell I now have a full picture of where and how the resources/data transfer etc are happening in our beloved PyActiveStorage (well, in `Active`) - here's the memory/time chain for the case of a single netCDF4 file of 50M size, all serial, and all on a GH Actions machine (which is OK since I am the sole user of it when running the test, but numbers ma
y vary from run to run by a certain small percentage); numbers are for `Active._version = ` (the one that uses Kerchunk, and should be the closest to active storage proper:

The stack is: `SingleHdf5ToZarr` -> JSON dump -> load Zarr Group -> have a Zarr reference file (image) -> select chunk -> send back chunk coords to AS -> get result from AS

### S3 (data is in an S3 bucket on Minio)

- entire `Active` (end-to-end): 617M / 167s
- `SingleHDF5ToZarr`: 66M / 0.23s
- JSON dump: 330M / 163s
- load Zarr group (includes JSON dump): 337M / 166s


### Local (data is available on disk)

- entire `Active` (end-to-end):  881M / 7.9s
- `SingleHDF5ToZarr`: 67M / 0.07s
- JSON dump: 348M / 6.6s
- load Zarr group (includes JSON dump): 495M / 7.8s

So it's pretty obvious there is data transfer at least once: at the Kerchunk chunks to JSON dump step; somewhere else along the stack after the Zarr-reference file has been loaded data is mishandled in memory leading to unnecessary memory clogging, but at least for the S3 case, it seems that the only actual data transfer to Client is happening at the JSON dump step, given that that takes the bulk of the time `Active` runs for. I need to figure out if/how we can get rid of the JSON dumping, otherwise we're fairly hosed :+1:

**Comment by bnlawrence** [comment]
Just so I understand this. The netCDF file is compressed right? What's the grid of the data in it? What is the chunking? (I am just trying to work out why we have >300M of json from 50M of data? The json should be the kerchunk chunk index right? Is the netCDF file itself sensible chunked?)

**Comment by bnlawrence** [comment]
(There is also that configuration option which if set wrong, means they load all the data into the json file as an "optimisation")

**Comment by valeriupredoi** [comment]
@bnlawrence the file created by the vanilla creator:
```python
        make_vanilla_ncdata(filename=s3_testfile,
                            chunksize=(3, 3, 1), n=150)
```
so a 150x150x150 with no compression, no filters, chunking is horrendous indeed. The JSON file itself is only 45M on disk, just a wee smaller than the actual netCDF data file (which is ~50M on disk)

**Comment by bnlawrence** [comment]
Is there any chance we are reading that json file every time we process a chunk, or do a test? Are those the timings per chunk, or per test, or per set of tests?

**Comment by valeriupredoi** [comment]
> Is there any chance we are reading that json file every time we process a chunk, or do a test? Are those the timings per chunk, or per test, or per set of tests?

per test, see the [test module](https://github.com/valeriupredoi/PyActiveStorage/blob/add_storage_options/tests/s3_exploratory/test_s3_performance.py) see the [GA action](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/6298953286/job/17098771135?pr=146) under the "Analyze S3 and local test performance" step - I think I am now understanding very well what's the hap, reading kerchunk's hdf5.py module, one sec will post findings

**Comment by valeriupredoi** [comment]
holy mother of Jeebus! Rechunking from (3, 3, 1) to (10, 10, 10) for the same 150x150x150 file gets us **HUGE** speedups and memory saves: see https://github.com/valeriupredoi/PyActiveStorage/actions/runs/6312570050/job/17138886865?pr=146 -

### S3 (data is in an S3 bucket on Minio)

- entire `Active` (end-to-end): 87M / 0.55s
- `SingleHDF5ToZarr`: 60M / 0.17s
- JSON dump: 64M / 0.49s
- load Zarr group (includes JSON dump): 65M / 0.51s


### Local (data is available on disk)

- entire `Active` (end-to-end):  98M / 0.14s
- `SingleHDF5ToZarr`: 60M / 0.05s
- JSON dump: 64M / 0.09s
- load Zarr group (includes JSON dump): 67M / 0.11s

**Comment by valeriupredoi** [comment]
same results when running locally, now with detailed Kerchunk timing:

### 3-3-1 chunking

Result
```
a = {'n': 8, 'sum': array([[[1355404.]]])}, axis = None, dtype = None, out = None, keepdims = False
```
Kerchunk timing
```
Kerchunking file /home/valeriu/PyActiveStorage/tests/s3_exploratory/test_data/test_bizarre.nc with variable data for storage type None
Storage type None
Translation begins
Transfer attrs took: 0.001699686050415039
Running translator
cinfo (part of visititems) took: 2.6562392711639404
H5 object Kind f
Transfer attrs took: 0.0005955696105957031
chunk info storaging took: 3.091123580932617
Running translator
cinfo (part of visititems) took: 6.866455078125e-05
H5 object Kind i
Transfer attrs took: 0.0007214546203613281
chunk info storaging took: 2.0742416381835938e-05
Running translator
cinfo (part of visititems) took: 8.440017700195312e-05
H5 object Kind f
Running translator
cinfo (part of visititems) took: 7.963180541992188e-05
H5 object Kind i
Transfer attrs took: 0.0007498264312744141
chunk info storaging took: 2.3365020751953125e-05
Running translator
cinfo (part of visititems) took: 6.747245788574219e-05
H5 object Kind f
Running translator
cinfo (part of visititems) took: 6.818771362304688e-05
H5 object Kind i
Transfer attrs took: 0.0006330013275146484
chunk info storaging took: 2.2649765014648438e-05
Running translator
cinfo (part of visititems) took: 5.054473876953125e-05
H5 object Kind f
Visit items took: 6.826631307601929
Trsnafer attrs and visit items took: 6.828451633453369
json encode took: 0.20699334144592285
Translate took: 7.035499334335327
```
## 10-10-10 chunking

Result
```
a = {'n': 8, 'sum': array([[[1355404.]]])}, axis = None, dtype = None, out = None, keepdims = False
```

Kerchunk timing:
```
Kerchunking file /home/valeriu/PyActiveStorage/tests/s3_exploratory/test_data/test_bizarre.nc with variable data for storage type None
Storage type None
Translation begins
Transfer attrs took: 0.005974292755126953
Running translator
cinfo (part of visititems) took: 0.028586149215698242
H5 object Kind f
Transfer attrs took: 0.0006480216979980469
chunk info storaging took: 0.015633106231689453
Running translator
cinfo (part of visititems) took: 7.009506225585938e-05
H5 object Kind i
Transfer attrs took: 0.0007061958312988281
chunk info storaging took: 1.7404556274414062e-05
Running translator
cinfo (part of visititems) took: 5.125999450683594e-05
H5 object Kind f
Running translator
cinfo (part of visititems) took: 6.389617919921875e-05
H5 object Kind i
Transfer attrs took: 0.0004954338073730469
chunk info storaging took: 3.24249267578125e-05
Running translator
cinfo (part of visititems) took: 3.910064697265625e-05
H5 object Kind f
Running translator
cinfo (part of visititems) took: 4.3392181396484375e-05
H5 object Kind i
Transfer attrs took: 0.0004894733428955078
chunk info storaging took: 1.52587890625e-05
Running translator
cinfo (part of visititems) took: 3.790855407714844e-05
H5 object Kind f
Visit items took: 0.07573843002319336
Trsnafer attrs and visit items took: 0.08198189735412598
json encode took: 0.0013606548309326172
Translate took: 0.08354067802429199
```

**Comment by valeriupredoi** [comment]
Chunks (75, 75, 75) doubles speedup :clown_face:

**Comment by valeriupredoi** [comment]
So more test results: in [latest test](https://github.com/valeriupredoi/PyActiveStorage/actions/runs/6313871715/job/17142905423?pr=146) I am creating a 500x0500x500 data file with chunks=(75, 75, 75) - the file (which I also created locally) is 1.1G in size. Local AS takes 0.1s and needs 100M of RES memory; S3 AS takes 0.28s and needs 83M of RES memory - numbers check out since I ran local AS on my laptop and it took 0.3s (slightly longer since I am printing stuff to screen - printing takes a lot in these very short cases) and needed 100M of RES mem :partying_face: 

@markgoddard I am afraid of abusing the GA machine with large files (I think about 2G is the most I can use), maybe it'd be good if you created a fairly hefty file (10G maybe?) and put it on Minio and tested with it, when you get a bit of time - chunking is absolutely paramount so maybe a (200, 200, 200) chunks for that? :beer:

**Comment by valeriupredoi** [comment]
chaps @bnlawrence @davidhassell @markgoddard - I'd like to merge this now so we have the tests available in `main` (for deliverable and other formal reasons, but also, so we can continue looking at performance); incidentally, this PR also cleans up the way we call `SingleHdf5ToZarr` from Kerchunk (it actually increases performance this way!) - could I ask one of yous to have a looksee and give me a review please - don't have to be super careful review, this doesn't break anything :grin:

**Comment by valeriupredoi** [comment]
I'll merge this for now - we can always PR improvements :grin:

**Pull request merged**
